### ISSUE TITLE
add cypress tests for row resizing feature

### ISSUE THREAD

**Issue by cromatikap** [cromatikap/reactgrid#1]
on this branch: https://github.com/cromatikap/reactgrid/tree/row-resize-feature

**Comment by xdmaury** [comment]
Hi @cromatikap, I'm not very experienced with testing.

I tried implementing this, but the tested version doesn't have the functionality to adjust the row height.

Commands that I ran:

- terminal 1 : `npm run start`
- terminal 2: `npm run test:cypress`

**Comment by xdmaury** [comment]
I had forgotten to enable resizing on the rows and to create the function to add them in reactgrid.

**Comment by cromatikap** [comment]
Hi Maury, thanks for looking it up!

Did you succeed to run some of the tests that were made already? On my side the tests failed so not sure if it's me or simply that there were not fully maintained

> I had forgotten to enable resizing on the rows and to create the function to add them in reactgrid.

Yes that seems to be it, you'll need to add the feature to the grid used by the cypress test suite, thanks 💯

**Comment by xdmaury** [comment]
Yes, I created just one test, and it's ok. the other have some errors.

**Comment by xdmaury** [comment]
<img width="952" alt="image" src="https://github.com/user-attachments/assets/06b318c8-7ec1-40ef-bff1-cc621bcab639">

**Comment by cromatikap** [comment]
Well done! Thanks, I’ll review this thoroughly soon

**Comment by cromatikap** [comment]
- merged #2
